default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: wolo
  

development:
  <<: *default
  database: npcdc_app_development

test:
  <<: *default
  database: npcdc_app_test

production:
  <<: *default
  database: npcdc_app_production
  username: postgres
  password: wolo
