default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo
  port: 5432

development:
  <<: *default
  database: npcdc_app_development

test:
  <<: *default
  database: npcdc_app_test

production:
  database: npcdc_app
  <<: *default
  port: 5432
